settings:
  title: 'Output Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: output-logo-o.svg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: output-com # unique identifier
    name: output.com
    description: 'Main Output website.' # default=empty
    url: 'https://output.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api-output-com
    name: api.output.com
    description: 'Arcade API endpoint.'
    url: 'https://api.output.com'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    
